version: '3.9'

services:
  todo-app: 
    build: ./todo-app 
    container_name: todo-app 
    depends_on:
        - 'mongo'
    environment:
      - PORT=9000
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_ROOT_USERNAME=admin
    ports:
      - '9000:9000'
    volumes:
      - './todo-app:/app'
  mongo:
    image: 'mongo:latest'  
    container_name: mongo 
    ports:
      - '27017:27017'
    volumes:
      - ./mongodata:/data/db
    restart: always
  react-app:
      stdin_open: true
      build:
        context: ./todo-app-client 
        dockerfile: Dockerfile
      volumes:
        - './todo-app-client:/usr/src/app'
        - /usr/src/app/node_modules
      expose:
        - 3000
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
